version: '3.6'

services:
  mongo:
    image: mongo:4.0
    hostname: 'mongo.rocketchat.local'
    container_name: 'rocketchat-mongo'
    restart: always
    volumes:
      - rocketchat-mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rocketchat
    command: mongod --smallfiles --oplogSize 128 --replSet rs0

  mongo-init-replica:
    image: mongo:4.0
    depends_on:
      - mongo
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'

  rocketchat:
    image: rocketchat/rocket.chat:latest
    hostname: 'app.rocketchat.local'
    container_name: 'rocketchat-app'
    restart: always
    volumes:
      - rocketchat-uploads:/app/uploads
    links:
      - mongo:mongo
    ports:
      - 3000:3000
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo

volumes:
  rocketchat-mongo-data:
  rocketchat-uploads: